### ISSUE TITLE
Saving playlists to user account

### ISSUE THREAD

**Issue by ghost** [leahakb/jummming#10]
https://github.com/leahakb/jummming/blob/master/src/Components/App/App.js#L49-L50

Nice job using `.map()` and arrow functions' implicit return to get all of the track URIs in a single, concise line of code 👍 

Use `.then()` to reset the `Playlist`'s state _after_ the save playlist request is resolved. You don't need to use an `else` statement between invoking the `Spotify.savePlaylist()` function and clearing the state.

https://github.com/leahakb/jummming/blob/master/src/Components/Playlist/Playlist.js#L18

Use a `value` attribute instead of `defaultValue` and set it to `{this.props.playlistName}` so that your playlist's name resets properly after save.

**Comment by leahakb** [comment]
https://github.com/leahakb/jummming/blob/master/src/Components/App/App.js#L49-L50
  savePlaylist (){
    let tracks = this.state.playlistTracks;
      if(tracks.length && this.state.playlistName) {
        let trackURIs = tracks.map(trackIndex => trackIndex.uri);
        Spotify.savePlaylist(this.state.playlistName, trackURIs).then(() => {
          //Use .then() instead of else to reset the Playlist's state after the save playlist request is resolved
          this.setState({
            playlistName: 'New Playlist',
            playlistTracks: []
          });
        });
      }
    }
https://github.com/leahakb/jummming/blob/master/src/Components/Playlist/Playlist.js#L18
changed to value instead of defaultvalue
